### ISSUE TITLE
Not delivering pulses after long delay

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#10] opened 2017-05-26 21:04 UTC
If the pyboard remained connected to the host computer for ~2h, when it was finally armed and triggered, it signaled to have started the sequence, but failed to actually deliver any pulses.

I was able to reproduce this twice, and each time it was fixed by restarting, re-arming. and re-triggering the board. Ideally this would not happen, though. Both times the pyboard had already once succesfully delivered the sequence before the 2 hour wait.

**Comment by faymanns** [comment] 2017-05-29 08:37
Which sequence die you use? I tried it with a short test sequence on my computer and I could not reproduce it.
Is it only the laser that does not work or also the blue LED that indicates the pulses?

**Comment by TheChymera** [comment] 2017-05-29 13:52
Also the blue LED. I tried it with the demo sequence from the repository (8 events à 20s and 20Hz).

**Comment by faymanns** [comment] 2017-05-30 09:32
I still did not manage to reproduce the problem. I got the SD card from the lab this morning and tried it again with the demo sequence.

**Comment by faymanns** [comment] 2017-06-09 16:00
As we were not able to reproduce the bug, I will close this issue for now.

**Closed by faymanns** 2017-06-09 16:00 UTC
Labels: bug
